### ISSUE TITLE
Crash when opening DMs

### ISSUE THREAD

**Issue by VampireFlower** [DiscordMessenger/dm#10]
Tested on windows 10 23H2 using the MSVC compiled release. Switching from a server to direct messages causes the application to crash. No log and no error message. Not much information given to me to debug what's going on so i decided to leave an issue.
![Animation23](https://github.com/DiscordMessenger/dm/assets/68222518/88e800d5-8059-4eca-979e-9efbb370c30b)

**Comment by iProgramMC** [comment]
That's pretty strange.  Notice how there's a pdb file alongside your executables?  If you have Visual Studio you can drag DM onto it, and run it, and load debug symbols from that file. Otherwise I'm not totally sure how to debug this.

**Comment by Huskydude422** [comment]
I'm also experiencing the same error on Windows 10 1809 using the MSVC build

**Comment by Huskydude422** [comment]
Using my alt account it doesn't crash, so it might have something to do with my main account having a shit-ton of open dms

**Comment by iProgramMC** [comment]
Could be.  I suggest you try to compile it and try debugging there; VS2022 is about 7 GB in size with the desktop development with C++ option, so it should be fine

**Comment by Huskydude422** [comment]
Line 262:
Unhandled exception at 0x002F8FB5 in DiscordMessenger.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.

**Comment by iProgramMC** [comment]
Wow! That was unexpected. I'll release a hotfix soon.

**Comment by iProgramMC** [comment]
@Huskydude422 I have a feeling that this is triggered by having a DM channel whose name is too long. Could you try creating a really long channel in a server and navigating to the server with Discord Messenger?

**Comment by VampireFlower** [comment]
I made a channel with name `ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss`. Navigating to it with discord messenger doesn't crash the application but the channel refuses to load with the last opened channel in its place.

**Comment by iProgramMC** [comment]
I was able to trigger the issue using a long channel name in a guild.  This will be fixed in a future V1.01 build.
![image](https://github.com/DiscordMessenger/dm/assets/17717494/9f3203dc-3197-417a-a6db-46368074ebbd)
