### ISSUE TITLE
Bot Icon in Userpanel is missing

### ISSUE THREAD

**Issue by RF7391** [DiscordMessenger/dm#101]
Before:
![image](https://github.com/DiscordMessenger/dm/assets/156833337/dbbe9228-49f3-411f-8acf-0f051efda22a)
After:
![image](https://github.com/DiscordMessenger/dm/assets/156833337/c62e861d-673e-4966-9b09-f5bb928e870f)

**Comment by iProgramMC** [comment]
Assigned the bug label because we don't have a regression label right now.
