### ISSUE TITLE
It should use the date and time format that the system is configured to use

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#106]

**Comment by iProgramMC** [comment]
Says who?

**Comment by Zero3K** [comment]
I was just offering it as a suggestion. I'm not forcing you to add it if you don't want to.

**Comment by iProgramMC** [comment]
I'm going to reject this suggestion, because the available formatting functions aren't satisfactory (`SHFormatDateTimeW` appears to generate strings like `X minutes ago`, which I can't be arsed to update every minute..)

**Comment by Zero3K** [comment]
It only does that with FDTF_RELATIVE. https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shformatdatetimew gives more information about SHFormatDateTimeW.

**Comment by iProgramMC** [comment]
That's exactly what I was trying to replicate, the "Today at HH:MM" thing.

**Comment by Zero3K** [comment]
I don't know then.
