### ISSUE TITLE
Try restarting the app or using another token

### ISSUE THREAD

**Issue by Timunim** [DiscordMessenger/dm#109]
How do i get the correct token and clear the app data to do so?
![imagem](https://github.com/DiscordMessenger/dm/assets/132018762/e9c45cbd-17ac-4a6b-93b1-ec8eb59ad361)

**Comment by iProgramMC** [comment]
Are you trying to log in using a bot token? Discord Messenger currently only works with user tokens. According to the Discord documentation, close code 4013 means "Invalid Intent", which I'm pretty sure is bot specific: https://discord.com/developers/docs/topics/opcodes-and-status-codes
