### ISSUE TITLE
Discord Messenger crashes because of `Access violation` (out-of-bound access) if message is a single `@`

### ISSUE THREAD

**Issue by BadAimWeeb** [DiscordMessenger/dm#116]
Tested on version 1.06, MSVC build.

https://github.com/DiscordMessenger/dm/blob/53951a09061b04836d61589815761142891d6c89/src/discord/FormattedText.cpp#L745

![image](https://github.com/DiscordMessenger/dm/assets/29724654/a99ff836-c113-4725-bc0c-f1157e786d72)
![image](https://github.com/DiscordMessenger/dm/assets/29724654/11f64f2d-f2e5-488d-b008-7fe5419e2687)

Not sure why it crashed since the `for` loop LGTM, maybe bad optimization?

**Comment by iProgramMC** [comment]
> Not sure why it crashed since the `for` loop LGTM, maybe bad optimization?

Because `size_t` is unsigned, so `str.size()-2` has the chance to overflow. Oops, I'll fix it
