### ISSUE TITLE
Discord Messenger Voice Channels

### ISSUE THREAD

**Issue by PDoughboy** [DiscordMessenger/dm#127]
Should the voice channels be working for discord messenger? I am unable to join or use voice channels or make private calls using discord messenger MinGW on Windows XP 32-bit sp3.

**Comment by iProgramMC** [comment]
Currently voice chat support isn't implemented. If you'd like to add this feature before I do, send a PR!

**Comment by FemBoysAreCut3** [comment]
@iProgramMC Do you plan to add voice chat support in the near future?
