### ISSUE TITLE
Themes around other Windows versions etc.

### ISSUE THREAD

**Issue by hostedbyjustus** [DiscordMessenger/dm#128]
I'm incredibly happy with this project and love using it but I would also love to see different Themes implemented. Especially ones that fit Luna or Aero and thus future Windows versions. Since on those versions the UI looks a little out of place. Keep on the good work :)

**Comment by iProgramMC** [comment]
The trouble is that there's little customizability available for the default Win32 controls. I have been thinking of adding more themes but currently I'm not sure about the feasibility of such a feature. Please, if you know how to program for Win32, give it a try!
