### ISSUE TITLE
Sending screenshot from clipboard via DiscordMessenger is messed up in the official client

### ISSUE THREAD

**Issue by serega2004** [DiscordMessenger/dm#13]
**Description**
Self-explanatory

**Steps to reproduce:**
1. Take a screenshot with Alt+PrtSc/Ctrl+PrtSc
2. Paste it in the channel you want to send
3. Send it

**Version**
1.00-MinGW

**Screenshots**
![image](https://github.com/DiscordMessenger/dm/assets/66155894/85e2d66d-c731-4c8b-9504-0810b8c07ff9)
![image](https://github.com/DiscordMessenger/dm/assets/66155894/71d36ba2-cf52-4904-9afd-91f502353adf)

**Comment by iProgramMC** [comment]
Interesting issue.  It occurs to me that some pixels have their alpha value replaced with zero?

**Comment by veselcraft** [comment]
> It occurs to me that some pixels have their alpha value replaced with zero?

in fact it is

if u process this broken screenshot through the ffmpeg you'll get a normal one

```sh
ffmpeg -i unknown.png xp.jpg
```

ffmpeg just cuts off transparency value to automatically make it 255 and then converts it to jpeg, not as photoshop does this

btw this funny ffmpeg behaviour can reveal some hidden information by alpha channel. photoshop does not delete color info even if transparency is 100%, gimp does

**Comment by iProgramMC** [comment]
Indeed I recognized this issue because the screenshots were showing fine in Discord Messenger - the image loaders ignore the alpha channel.

**Comment by iProgramMC** [comment]
Can't reproduce the issue. What Windows version are you using? What is your current bit depth? I use Windows 11 22H2, tried with both alt-prsc & ctrl-prsc but the images come out fine.

**Comment by iProgramMC** [comment]
I found the issue without having to reproduce it.  This line https://github.com/DiscordMessenger/dm/blob/master/src/windows/ImageLoader.cpp#L189 is supposed say 255 << 24 rather than 255 << 16.

**Comment by iProgramMC** [comment]
Ok, as it turns out it's quite difficult to actually make sure alpha information is accurate coming from windows... that means for now I'll just force alpha to 255. Not a good solution, though. I encourage someone to come in and take a look at this.
