### ISSUE TITLE
[MSVC] VS C++ Redist is required to run this soft but it's not mentioned which one

### ISSUE THREAD

**Issue by veselcraft** [DiscordMessenger/dm#15]
Tried to run in on XP SP2, it swears "MSVCP140.dll is not found"

**Comment by WiseMatthack** [comment]
yeah same thing here on windows vista sp2, i tried to install VSC++ Redist 2015 but nothing changed

**Comment by iProgramMC** [comment]
Strange. Are you sure you installed the Visual C++ 2015 Redistributable Package?

**Comment by WiseMatthack** [comment]
well it seems so, msvco140.dll can be found in SysWOW64 and system32, so it should work without a problem. i'll try to reinstall it

**Comment by veselcraft** [comment]
> Strange. Are you sure you installed the Visual C++ 2015 Redistributable Package correctly?

 it refuses to install on xp sp2

**Comment by TheNachoBIT** [comment]
I think this is happening because the MSVC version got accidentally released as a Debug version instead of Release or RelWithDebInfo.

Have you guys tried the MinGW version to see if that one runs well?

**Comment by pingiun** [comment]
I installed this version of the redistributable package, which made the MSVC version work on Windows XP: https://www.microsoft.com/en-gb/download/details.aspx?id=48145

**Comment by WiseMatthack** [comment]
> I installed this version of the redistributable package, which made the MSVC version work on Windows XP: https://www.microsoft.com/en-gb/download/details.aspx?id=48145

still doesn't work for me on vista :(

**Comment by WiseMatthack** [comment]
> I think this is happening because the MSVC version got accidentally released as a Debug version instead of Release or RelWithDebInfo.
> 
> Have you guys tried the MinGW version to see if that one runs well?

the minGW version runs fine :)

**Comment by TheNachoBIT** [comment]
> > I think this is happening because the MSVC version got accidentally released as a Debug version instead of Release or RelWithDebInfo.
> > 
> > Have you guys tried the MinGW version to see if that one runs well?
> 
> the minGW version runs fine :)

Then yeah, i'm guessing that the MSVC/Visual Studio Version was compiled with a "Debug" profile.
The Debug profile actually adds a connection to Visual Studio (not sure why, probably for deep debugging) and it uses an .dll that is from VS 

That's why MSVCP140.dll is *probably* not found. Because that's not a Windows DLL, that's a Visual Studio DLL with an absolute path.

(This is a theory/guess btw, this happened to me when i was starting with C++ on Windows, and wanted to share the binaries that i coded with other people lol)

**Comment by TheNachoBIT** [comment]
If you want a solution, i suggest sticking with the MinGW version.

Internally the differences are not too many other than:
- MSVC is a version compiled with a closed-source compiler (called MSVC, lol).
- MinGW is compiled with an open-source compiler (gcc or clang).

And they're both so advanced that they're going to function exactly the same without any performance difference :D

**Comment by iProgramMC** [comment]
> I think this is happening because the MSVC version got accidentally released as a Debug version instead of Release or RelWithDebInfo.

I'm pretty sure I provided a release build. Debug builds would ask for MSVCP140**D**.dll. Also I'm not sure what RelWithDebInfo is, I guess it's customary to have two types of release, but I don't.

**Comment by iProgramMC** [comment]
> And they're both so advanced that they're going to function exactly the same without any performance difference :D

Yes, they're nearly identical, but the MinGW version won't load webp (I couldn't find a precompiled webp library to link with in the MinGW version)

**Comment by TheNachoBIT** [comment]
> > I think this is happening because the MSVC version got accidentally released as a Debug version instead of Release or RelWithDebInfo.
> 
> I'm pretty sure I provided a release build. Debug builds would ask for MSVCP140**D**.dll. Also I'm not sure what RelWithDebInfo is, I guess it's customary to have two types of release, but I don't.

Oh yeah u right! That's why i said the "i think" because i had issues with sharing before that asked that .dll, that were fixed once i sent the Release version. So my bad ;_;

RelWithDebInfo is basically Release but you keep the debug symbols btw :D

**Comment by iProgramMC** [comment]
Heads up: make sure you install the 32-bit version of the redists because Discord Messenger's precompiled builds are 32-bit only!

**Comment by WiseMatthack** [comment]
i did! but it still did not work :(

**Comment by iProgramMC** [comment]
Could you run a `dir /s msvcp140.dll` and check if the path it was found in is located in your PATH environment variable? (System `sysdm.cpl` > Advanced > Environment Variables...

**Comment by iProgramMC** [comment]
Stale.
