### ISSUE TITLE
Problem with compiling Main.cpp

### ISSUE THREAD

**Issue by theblurry99** [DiscordMessenger/dm#2]
Let me start that I am not a good dev, my C++ knowledge is very basic.

So I was trying to build 'dm' using MinGW under Windows. Until the `main.cpp` file, everything compiled nicely, once it's time for the main file, I get `Error 1` from make with this log:
![image](https://github.com/DiscordMessenger/dm/assets/87043335/b9d3941f-9c72-4a0d-9a5a-c4999b1651d1)

Trying to find a possible solution while writing this, maybe someone could help me out?

**Comment by theblurry99** [comment]
Turns out it was a weird mistake with the order of the code?
![image](https://github.com/DiscordMessenger/dm/assets/87043335/1d80fd07-47bb-4bfd-86ac-cca6b807171b)

After moving the highlit snippet starting at line 480, below the `_fail` statement, code compiled fine now...

Looks like it came out with the recent commit to `main.cpp`, might be worth taking a look!

**Comment by iProgramMC** [comment]
Well, it's my fault.  In fact I did try to ensure that that doesn't happen, but yeah, that just flew past me for some reason.
