### ISSUE TITLE
Client crashes when switching to DMs

### ISSUE THREAD

**Issue by ergosteur** [DiscordMessenger/dm#21]
Title says it - the client crashes when switching to DMs. No error. 
Happens consistently with my main account, which does have a lot of DM conversations. Does not occur with my second/test account. 

Same behaviour with the MSVC and MinGW versions, on both Windows 11 and XP. 

Willing to test/provide more info.

**Comment by iProgramMC** [comment]
Hello! I've recently fixed a similar issue: #10. I suspect that you are running into this issue as well. A future build of the app will have this issue fixed. Maybe try compiling master to avoid it for now?

**Comment by iProgramMC** [comment]
Just to make sure, trigger the crash again and go into the event viewer, it will tell you the exception number (which should say something like "stack overrun detected")

**Comment by ergosteur** [comment]
Confirmed, building from master fixes it! Thanks.
