### ISSUE TITLE
DM throws a hard error if image doesn't exists?

### ISSUE THREAD

**Issue by Hazuki-san** [DiscordMessenger/dm#23]
![image](https://github.com/DiscordMessenger/dm/assets/27200811/3f37db04-e893-403c-a35c-90f7eec976dc)

**Comment by iProgramMC** [comment]
You can safely ignore this error. Perhaps I should just make it render an error graphic, and that's it.

**Comment by iProgramMC** [comment]
This will no longer show up if you didn't open the image as of https://github.com/DiscordMessenger/dm/commit/f18d4e1886e21b91cab5355f2d3c7862b8120cc0.
