### ISSUE TITLE
One of my server cause the DM client to crash

### ISSUE THREAD

**Issue by Hazuki-san** [DiscordMessenger/dm#24]
Is there any log or debug version so I could send in the log?

**Comment by iProgramMC** [comment]
Does that server happen to have a channel with a name longer than 63 characters? I've fixed a bug with regards to that yesterday in master, try compiling there or wait for V1.01 to be released.

**Comment by Hazuki-san** [comment]
No, the server has the only 25 characters in length. The name includes 2 symbols which is `'` and `<` but that shouldn't be the case.

**Comment by iProgramMC** [comment]
I was asking if the server has a channel whose length is more than 63 characters. To my knowledge Discord allows up to 128 characters in the channel's name. The side effect is that on master the names will be truncated, and on V1.00, a crash will occur

**Comment by iProgramMC** [comment]
I will close the issue now as I believe it to be fixed. If you can find a way to trigger this crash without having an obscenely long channel name, I'll reopen it.
