### ISSUE TITLE
Email and password support (it could be possible)

### ISSUE THREAD

**Issue by RF7391** [DiscordMessenger/dm#3]
There is a program called miranda ng that manages to log into discord through email and password, it works from windows xp to 11,
Maybe taking a look at this program can help with development (PS. Use the development version of miranda ng to access it)
![image](https://github.com/DiscordMessenger/dm/assets/156833337/05d3eec9-6ddf-4b9c-9337-809e386bbd55)

**Comment by RF7391** [comment]
Ah i see,
in personal experience ive put it on 5 miranda clients and have logged on many times and i have had no issue

**Comment by RF7391** [comment]
I think by putting a warning , it'll be fine

**Comment by Zero3K** [comment]
I agree.
