### ISSUE TITLE
Odd Scrollbar behavior?

### ISSUE THREAD

**Issue by insanemadman622** [DiscordMessenger/dm#30]
When scrolling through the member list, the scroll bar seems to snap back to the top of the list. See attached for demonstration. Unsure if this is intentional.
Windows 11, MSVC

https://github.com/DiscordMessenger/dm/assets/169422799/719a4fb0-4e81-41ec-a6ff-1cb9a58cf19e

**Comment by Zero3K** [comment]
I think this issue also occurs in the channel list.

**Comment by Zero3K** [comment]
It is still happening for me.

**Comment by Zero3K** [comment]
But only when the window is maximized.

**Comment by iProgramMC** [comment]
Happens not for me anymore.

**Comment by Zero3K** [comment]
Never mind, it was fixed after all.
