### ISSUE TITLE
Odd behavior when deleting messages

### ISSUE THREAD

**Issue by insanemadman622** [DiscordMessenger/dm#31]
When i delete messages with the main message header, the username is removed, but the link still remains. The video explains better. Windows 11, MSVC

https://github.com/DiscordMessenger/dm/assets/169422799/cd182f7a-22a9-4294-b236-8c950c50a77c

**Comment by iProgramMC** [comment]
This looks like a redraw bug. Before hovering over your username, could you drag that part offscreen and then back in view?

**Comment by insanemadman622** [comment]
https://github.com/DiscordMessenger/dm/assets/169422799/1e7cfb8e-1350-4f91-bdc8-4630f6772619

**Comment by iProgramMC** [comment]
Yep, that's definitely a redraw bug. I'll take a look & fix it as soon as possible.
