### ISSUE TITLE
Support for other chat protocols? e.g. IRC, XMPP, Escargot, Matrix, Tox

### ISSUE THREAD

**Issue by Darthagnon** [DiscordMessenger/dm#38]
Would it be possible to add support for other chat protocols to `dm`? 

Discord leads in terms of user-interface, but leaves a lot to be desired regarding privacy and long-term availability of data. Older protocols like IRC and XMPP are more federated (and may be compatible out of the box with older Windows), but are not very user-friendly/lack good clients. Matrix and Tox are both modern and "secure" and more decentralised, but most Matrix clients have horrible UI, and Tox (secure enough to be favoured by pirates and ransomeware groups) has mostly outdated clients.

**Comment by iProgramMC** [comment]
Not planned.  Despite that, you can probably rip out the discord specific stuff once I separate the backend (src/discord/) into its own submodule.

**Comment by RF7391** [comment]
> Would it be possible to add support for other chat protocols to `dm`?
> 
> Discord leads in terms of user-interface, but leaves a lot to be desired regarding privacy and long-term availability of data. Older protocols like IRC and XMPP are more federated (and may be compatible out of the box with older Windows), but are not very user-friendly/lack good clients. Matrix and Tox are both modern and "secure" and more decentralised, but most Matrix clients have horrible UI, and Tox (secure enough to be favoured by pirates and ransomeware groups) has mostly outdated clients.


Check out Miranda NG, most of these protocols are supported and it works on windows xp with a good gui as it was made in the xp days and still gets support
