### ISSUE TITLE
Issue with sleeping and resuming with Discord Messenger running

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#40]
When sleeping and resuming with it running, a message that gets sent doesn't show up in the channel. I have to switch to a different channel, then back to the previous one and then send the message.

**Comment by iProgramMC** [comment]
Well because your computer is sleeping it can't receive messages. However they should be there if you restart.

**Comment by Zero3K** [comment]
No, I mean, when I resume, I am unable to send a message to the currently viewed channel. I have to switch to a channel and back to be able to send it.

**Comment by Zero3K** [comment]
You can replicate it by doing the following:

1. Have Discord Messenger open and viewing a channel.
2. Open Control Panel by running control in the Run Dialog Box opened by pressing Win + R.
3. Open Network and Sharing Center.
4. Click Change adapter settings
5. Disable and enable your network adapter.
6. You should get an error message saying that the connection cannot be made.
7. Click OK.
8. Try to send a message, it will be entered but not shown until you close and re-open it and view the channel.

**Comment by iProgramMC** [comment]
I don't think that Discord Messenger re-opens the websocket when it gets disconnected. This is something that should be looked into.

**Comment by Zero3K** [comment]
Now it shows as sending but doesn't change its status until I restart the program.

**Comment by Zero3K** [comment]
Any news regarding this?

**Comment by Zero3K** [comment]
Doing the steps I wrote earlier also causes the member list to no longer display.

**Comment by iProgramMC** [comment]
This is pretty much fixed.
