### ISSUE TITLE
Tenor support

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#47]
It would be nice if it supported the animated image that is shown when a message contains a link to one on its platform.

**Comment by iProgramMC** [comment]
Although Discord claims it's embedding a GIF, in reality it embeds an mp4.  I don't have support for mp4 files.  Therefore, this won't be added anytime soon.

**Comment by Zero3K** [comment]
Maybe much later then?

**Comment by iProgramMC** [comment]
I was thinking to embed LibVLC to allow for playback of mp4 files. But I was also thinking that this'd have to be optional seeing as we target all kinds of hardware, slow or fast, with DM.

**Comment by MP36ctrl** [comment]
could VLC possibly allow Video calls in the future?

**Comment by MP36ctrl** [comment]
fair, was asking moreso if it could stream content from others in theory as a efficient solution
