### ISSUE TITLE
Another issue with the display of a username in the DM part of Discord Messenger

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#49]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/01700e23-9ce2-4527-941e-3bec71032e0b)

The squares should be showing up as a heart on both sides.

**Comment by iProgramMC** [comment]
Please avoid filing issues for trivial things.  No, it seems Win32 doesn't render those characters.  What can I do about it?

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/a01dab7a-0d8f-4c94-b5a3-4ebe0d973c25)

It renders fine in the Title Bar though (but not in the list and in the taskbar).

**Comment by iProgramMC** [comment]
Yes, UNICODE is being defined. It's not that simple. Could you copy paste the display name in here?

**Comment by Zero3K** [comment]
🩷Lily🩷

**Comment by iProgramMC** [comment]
Because this emoji was added in 2022, support for it in Win32 is limited.  Therefore this is not fixable by Discord Messenger.

**Comment by Zero3K** [comment]
Then why does it show properly in the title bar? Also, does that mean that the other cases of squares won't be fixed?

**Comment by iProgramMC** [comment]
The title bar is not rendered by Win32, but by whatever modern crap Microsoft is doing.

This does mean other cases of replacement characters won't be fixed.

**Comment by Zero3K** [comment]
Unless someone else fixes it and makes a PR for it.

**Comment by Zero3K** [comment]
Okay.
