### ISSUE TITLE
Leaving Discord Messenger open for a while causes images and menu entries to stop being displayed

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#51]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/974f2648-b0cc-4708-8345-5ded4d5415ff)

**Comment by iProgramMC** [comment]
Looks like bitmaps are being invalidated.  The fix for now is to restart the app but this should really be fixed.

**Comment by Zero3K** [comment]
I wonder why the menu items are also not showing up when the bitmaps stop showing up.

**Comment by iProgramMC** [comment]
What menu items?

**Comment by Zero3K** [comment]
All of them.

**Comment by iProgramMC** [comment]
All of them is too vague.  Show screenshots of exactly what you are talking about. What menu you are talking about, and what specific items.

**Comment by Zero3K** [comment]
I think it is a GDI Handle leak according to this:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/68ccf152-77fe-4cec-b54b-db8f15b433f9)

That number keeps going up every few seconds.

**Comment by iProgramMC** [comment]
Every few seconds is a bit strange.

Also, how many hours of browsing do you typically get before running into this issue?

**Comment by Zero3K** [comment]
I'll reply when it happens again with how long it took to happen.

**Comment by Zero3K** [comment]
It took around 2 hours and 40 minutes for it to happen. The GDI Handle count stopped being counted at 9,999.

**Comment by iProgramMC** [comment]
I see.

**Comment by iProgramMC** [comment]
Fixed in upstream. It turns out there is an issue with the guild list control. It didn't free the result to LoadBitmap().

**Comment by Zero3K** [comment]
There's still another leak that is happening.

**Comment by iProgramMC** [comment]
As far as I know, I've fixed all known leaks. I've tried dragging the window continuously outside of the screen and it doesn't increase the GDI object/handle counter too much.

A tip I can give you to track down the leak is to open it up in Windows XP (or Windows 7 with the basic theme), drag a window over it and slowly reveal every control in the app. That's how I started noticing that the guild list is leaking GDI objects.

**Comment by Zero3K** [comment]
Then I wonder why the GDI Handles went up to 9,999 when I left it alone for a while.

**Comment by iProgramMC** [comment]
I gave you a way to debug it.

**Comment by Zero3K** [comment]
I did that and see that the Bitmap number is still going up (but not as quickly).

**Comment by iProgramMC** [comment]
OK, I've fixed another handle leak. It should be fine now!
