### ISSUE TITLE
Loading all avatars of the members of a channel

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#58]
It would be nice if it loaded all avatars of the members of a channel when it is viewed.

**Comment by iProgramMC** [comment]
It does, but just the first 100. Yes it should load more when you scroll down, but you can probably tell that the member list is half baked as of now and will be developed.

Please note: this program is in beta.  I'm aware of most of the issues you are bringing up.

**Comment by Zero3K** [comment]
It does load the rest of the avatars of the first 100 members when I scroll down.
