### ISSUE TITLE
[REGRESSION] The start maximized option in the Appearance tab of its Preferences no longer works properly

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#62]
Having it checked is the same thing as having it unchecked.

**Comment by Zero3K** [comment]
Windows 11 23H2

**Comment by Zero3K** [comment]
This issue is still occurring for me.

**Comment by iProgramMC** [comment]
`ShowWindow` is never called on `g_Hwnd` (the main window). Instead, the window is made visible through the `WS_VISIBLE` flag.

But I will make a commit to call `ShowWindow` so that perhaps your issue will be fixed.

**Comment by Zero3K** [comment]
Thanks. That fixed it.
