### ISSUE TITLE
Issue with scrolling in a channel

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#65]
When scrolling up in a channel, then minimizing and restoring the window, the scrollbar position is forgotten and it is at the bottom instead.

**Comment by iProgramMC** [comment]
This happens whenever a size change occurs.  There's no easy way to fix this, but I'll see what I can do.

**Comment by Zero3K** [comment]
Any news regarding this?

**Comment by iProgramMC** [comment]
Believe it or not, you don't need to inquire about it! If there weren't any updates posted, you can probably assume that there are no news regarding specifically this issue.

**Comment by Zero3K** [comment]
This issue is still occurring (but not as bad as it was). This is what I scrolled to at first:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/0ec54479-8b9f-4ff9-862f-2c6aebfe99d3)

This is what I scrolled to next:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/f567c61b-cdb9-4032-a3b8-6b938e9c24c4)

Minimizing and restoring causes the position to change back to where it is in the first image.

**Comment by iProgramMC** [comment]
Doesn't happen for me, are you sure you're using the latest build?

**Comment by Zero3K** [comment]
Yes.

**Comment by Zero3K** [comment]
I have it maximized.

**Comment by Zero3K** [comment]
Having it not be maximized results in the issue not happening.

**Comment by Zero3K** [comment]
Never mind, it was fixed after all.

**Comment by Zero3K** [comment]
I thought it was fixed but it is not. It also happens when the window is not maximized.

**Comment by iProgramMC** [comment]
I don't know. I don't see any of the current behavior as a bug.

**Comment by Zero3K** [comment]
Really? No other program works like that.

**Comment by iProgramMC** [comment]
Like what? Could you upload a demo video?

**Comment by Zero3K** [comment]
https://github.com/DiscordMessenger/dm/assets/6194332/8cd29539-ed3b-46ec-8039-cd4c9c88c34a

**Comment by iProgramMC** [comment]
OK, that looks like a problem. I'll re-open the issue and take a look.

**Comment by iProgramMC** [comment]
Could you send the invite link to this Discord server?

**Comment by Zero3K** [comment]
It has been sent.

**Comment by iProgramMC** [comment]
Thanks. Was able replicate this issue.

**Comment by iProgramMC** [comment]
OK, it looks like I've fixed this bug.

**Comment by Zero3K** [comment]
I can confirm that it has been fixed.
