### ISSUE TITLE
Add support for slash command reply messages

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#68]
Discord Messenger:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/a12a371a-b554-450b-9933-7dd4822b0e3d)

Discord Web Client:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/10a9096d-6840-4873-9e5b-7ab96e285503)

**Comment by iProgramMC** [comment]
I've rephrased your issue, but I am going to close it because I don't plan on implementing slash commands any time soon.
