### ISSUE TITLE
Switching between servers and channels causes RAM usage to increase

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#69]
*subject*

**Comment by iProgramMC** [comment]
Obviously.  Not all servers and channels are loaded entirely at the same time.  Or is the RAM usage so out of whack that it smells more like a memory leak?

**Comment by Zero3K** [comment]
I do not know. You could look and see if there is one. I think the RAM amount could be lowered by some method every now and then so it doesn't get out of hand.

**Comment by iProgramMC** [comment]
I've switched across several tens of channels.  It seems the RAM usage only increases when you actually load new messages, which is completely normal - RAM is used to store the messages after all.  Although yes, maybe invalidating all but the last 50 messages in a channel sometimes is due.

**Comment by iProgramMC** [comment]
I'm going to close this because:
1. RAM usage of course increases because all the channels are being kept in memory.
2. A few resource leaks were actually fixed which should soften the load on RAM. (#51)
