### ISSUE TITLE
Feature Request - Github Actions for pre-built binaries

### ISSUE THREAD

**Issue by SirForte** [DiscordMessenger/dm#7]
exactly what it says in the title

**Comment by iProgramMC** [comment]
This would be better than me putting out binaries manually, problem is though, how in the world would I get GitHub actions to build a MSVC / MinGW project?

**Comment by iProgramMC** [comment]
Ok, I'll admit, GitHub Actions is out of my area of expertise at the moment, maybe you or someone who knows could help with that?

I'm going to close this issue for now. I may add support for GitHub Actions in the future myself, or someone can create a PR to do it for me.

**Comment by ArjixWasTaken** [comment]
I randomly found this project and randomly looked at the issue, and sadly I am not interested in making a PR for that.
But I can give some repositories to take inspiration from.

**Comment by Zero3K** [comment]
Thanks for offering one that compiles a build done via MSVC when a commit is made.
