### ISSUE TITLE
Discord Messenger keeps going back to the topmost server somehow

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#70]
I think it happens when resuming from sleep or when the laptop turns off because of low power after saving the state to disk and/or RAM   and then restores it when it is turned back on while it is charging.

**Comment by iProgramMC** [comment]
Do you _think_? Or do you have a way to reproduce it?

**Comment by Zero3K** [comment]
I haven't come up with that yet but I will pay attention this time.

**Comment by Zero3K** [comment]
It's the latter that is causing it.

**Comment by iProgramMC** [comment]
OK, it turns out this happens when the websocket gateway connection is interrupted, but your internet connection is still up. I'll take a look.
