### ISSUE TITLE
Discord messenger crashes when it loads the vencord server

### ISSUE THREAD

**Issue by RF7391** [DiscordMessenger/dm#74]
Something in the Vencord discord server is crashing Discord messenger, might be a good idea to see just incase this happens somewhere more important

**Comment by RF7391** [comment]
From my experience just clicking on the server icon would crash the program, i have a feeling its not just that channel, I'll test with the next update to see if it still happens tho

**Comment by iProgramMC** [comment]
You can download the latest GitHub Actions artifact: click that little tick next to the commit description, then "details" on the only entry, then "Summary" and download the artifact.

Here's what I want you to do first though. I want you to trigger the crash again, then go quickly into Event Viewer, Application, then find one of the latest Error logs, here's an example:
![image](https://github.com/DiscordMessenger/dm/assets/17717494/66e3ec73-cb46-403c-b6a7-9693d85d84b5)

I can cross-reference the fault address with the built-in pdb file afterward.
