### ISSUE TITLE
Show errors in a log file instead of dialog boxes

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#77]
*subject*

**Comment by iProgramMC** [comment]
I don't want to hide all errors from the user.  Although really I should hide some of them (the avatar and attachment ones for instance), I happen to run into some myself when using older Windows versions.

**Comment by Zero3K** [comment]
Oh, then how about placing them in a separate tab that shows something in its title to notify the user to new errors (such as a (1) or a dot)?

**Comment by Zero3K** [comment]
Well?

**Comment by iProgramMC** [comment]
I have closed this issue as not planned.

**Comment by Zero3K** [comment]
Okay.
