### ISSUE TITLE
A certain channel isn't having its new messages status cleared when it is viewed for a few seconds

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#78]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/e1b381c7-9558-4808-b392-d28bfbd4319c)

That channel is having the mentioned issue.

**Comment by iProgramMC** [comment]
Could you reach out via email and send me the invite to the server?

**Comment by iProgramMC** [comment]
Now, I think this was fixed, let me know if it wasn't so I can re-open the issue.

**Comment by Zero3K** [comment]
It's still happening for me.

**Comment by iProgramMC** [comment]
Do you know of any other channels this happens in? I haven't had that happen in that specific one, though I had just joined the server.

**Comment by Zero3K** [comment]
Now it works for that room.
