### ISSUE TITLE
Issue with the display of some usernames

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#82]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/445d8f71-b302-468e-a647-a9369153810e)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/7472a557-1502-4e08-a1be-5090ee59fe63)

**Comment by iProgramMC** [comment]
I don't see an issue.

**Comment by Zero3K** [comment]
The spacing is the issue.

**Comment by iProgramMC** [comment]
I guess those people set a crap-ton of spaces after the exclamation point. Like `!          Hey, I am an attention seeker`  It occurs to me that Discord collapses them all into one space. Discord Messenger renders names as their are, so in a way, this is intended.

**Comment by Zero3K** [comment]
! 亗ＧＯＤ亗 is one such username. There's only one space in between the ! and the symbol.

**Comment by Zero3K** [comment]
Oh, I see the additional spaces in the "dm @username" text.

**Comment by iProgramMC** [comment]
So that's that then. Not a bug, you just didn't understand why something was happening.
