### ISSUE TITLE
Issue with text that exceeds the width of the window

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#83]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/e75fdf79-621b-4d74-b84e-e50f810255fc)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/7ccc3519-41cf-4b4c-a332-beba5db9d639)

**Comment by iProgramMC** [comment]
Looks like I forgot to close this issue. Fixed as of a263528ab1be918d1d7ce037aeddc98c11ae3ff4.
