### ISSUE TITLE
Another issue with sleeping and resuming with Discord Messenger running 

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#84]
When sleeping and resuming with it running, it tells me that a timeout occurred.

**Comment by iProgramMC** [comment]
Add an image so that I know what you're talking about.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/bc2d7737-d5b7-43e0-832f-2767fe5cb887)

**Comment by iProgramMC** [comment]
Yes, press OK and it should attempt to reconnect.

**Comment by Zero3K** [comment]
Okay.
