### ISSUE TITLE
Unicode support is missing in Discord Messenger

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#85]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/ea6f30d4-d07b-475e-a4a1-63c5b08b2738)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/006a0c01-4fd7-4fbf-b91a-a7ca019bc87f)

**Comment by iProgramMC** [comment]
Nope, it was actually always there, it just broke due to my crappy word wrapping hack.
