### ISSUE TITLE
Add welcome header

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#86]
Please take a look at the screenshots in #85.

**Comment by iProgramMC** [comment]
Currently I don't know of a way to use the Discord API to determine the first message in a channel. So this is kind of difficult to add.

**Comment by iProgramMC** [comment]
Ok, it looks like the official Discord client just detects when less than 50 messages are received.

**Comment by iProgramMC** [comment]
Here's what it looks like:
![image](https://github.com/DiscordMessenger/dm/assets/17717494/b65fa3f7-6a09-4395-a390-afdaaa0703c4)

**Comment by Zero3K** [comment]
Please consider adding the bold text that is centered and the "This is the beginning of the server." text below it (which is shown when viewing the first channel that was made in a Discord Server).
