### ISSUE TITLE
Thumbtack symbol is missing from a post in a certain channel even though it is shown elsewhere in the same post

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#87]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/0ea8915a-cd44-4c23-9a1e-f42f8bd9a440)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/5fd82221-c032-4e0a-9fc2-023e1dee848e)

**Comment by iProgramMC** [comment]
Related to #85.
