### ISSUE TITLE
I dont get how to use MinGW

### ISSUE THREAD

**Issue by MP36ctrl** [DiscordMessenger/dm#9]
Im confused on steps 3 & 4:

Ensure that both the MinGW bin/ AND msys bin/ directories are in your PATH.

Set **OPENSSL_INC_DIR and OPENSSL_LIB_DIR in your environment variables to your OpenSSL** include and library directories. If you want to remember the paths, edit the Makefile to use those as your defaults (but make sure to not check in your change when sending a PR!)

If you wish to use Shining Light Productions' distribution of OpenSSL-Win32, use the %OPENSSL_INSTALL%/include and %OPENSSL_INSTALL%/lib/MinGW directories for the include and lib dirs respectively.

**Comment by iProgramMC** [comment]
What confuses you here?

**Comment by RF7391** [comment]
Basically idk what it means to environment variables and idk what it means to set it to your open ssl

**Comment by iProgramMC** [comment]
To modify your environment variables, use the System control panel applet, go to Advanced, then click "Environment Variables".  Or type "Environment variables" in your start menu:
![image](https://github.com/DiscordMessenger/dm/assets/17717494/7113ba17-d214-4969-807f-8b0ad3947819)

Add two new environment variables called `OPENSSL_INC_DIR` and `OPENSSL_LIB_DIR`. Their values are the directory where the OpenSSL header files are located (usually `C:\Program Files (x86)\OpenSSL-Win32\include`), and where the OpenSSL library files are located respectively (usually `C:\Program Files (x86)\OpenSSL-Win32\lib\MinGW`).

I understand the difficulty in setting up the project, so soon I will be providing pre-built binaries for V1.00.

**Comment by iProgramMC** [comment]
Please close the issue if you aren't having any problems.

**Comment by RF7391** [comment]
Okki
