### ISSUE TITLE
Unsupported Media Type error on a certain URL

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#92]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/bee72171-4a38-47e8-b216-c13f043f528d)

Going to https://snag.gy/n6Ilde.jpg results in a redirect to https://snipboard.io/n6Ilde.jpg.

**Comment by Zero3K** [comment]
Maybe you can try having it grabbing the image from the URL that is in the post and replace the image that is shown with it when an error code is reported.

**Comment by iProgramMC** [comment]
No. Discord proxies images for a reason.

Was this error triggered by opening the image, or by just viewing it in the message list?

**Comment by Zero3K** [comment]
It happens when viewing it both ways.

**Comment by iProgramMC** [comment]
This dialog no longer shows up for this error code without interaction as of 33a104f9.
