### ISSUE TITLE
Replies do not work

### ISSUE THREAD

**Issue by frickinfire** [DiscordMessenger/dm#94]
![image](https://github.com/DiscordMessenger/dm/assets/46013177/db457d8a-449e-4ad9-9503-127bc75dc953)
(i'm aware this isnt built with windows 10 in mind but this happens on 2000 and xp as well)

**Comment by iProgramMC** [comment]
Please provide some more context. What kind of message are you trying to send?

**Comment by frickinfire** [comment]
> Please provide some more context. What kind of message are you trying to send?

In this instance, I am trying to reply to my friend's message in a group DM with a simple text message. After sending the message, that pop-up appears. This also happens in servers and private DMs.

**Comment by iProgramMC** [comment]
I gotta be honest, I've never seen that happen before. Could you open up the network tab on the official Discord client, send a reply message and dump the "Payload" tab's contents? (Not the response or preview, and not the whole fetch request, as that contains your token)

**Comment by frickinfire** [comment]
> I gotta be honest, I've never seen that happen before. Could you open up the network tab on the official Discord client, send a reply message and dump the "Payload" tab's contents? (Not the response or preview, and not the whole fetch request, as that contains your token)
```{"mobile_network_type":"unknown","content":"cool","nonce":"1245831631562866688","tts":false,"message_reference":{"channel_id":"701099357465870336","message_id":"1245224212982136924"},"allowed_mentions":{"parse":["users","roles","everyone"],"replied_user":false},"flags":0}```
Here you go.

**Comment by iProgramMC** [comment]
I'm pretty sure this doesn't happen in servers.
