### ISSUE TITLE
Message BG Feature

### ISSUE THREAD

**Issue by RF7391** [DiscordMessenger/dm#95]
Add the ability to have a custom background for chats and panes
An Example of what i mean:
![image](https://github.com/DiscordMessenger/dm/assets/156833337/6c81fb25-9030-4c9b-abe9-da5d3d652f48)
with the ability of anchoring to a side or center or stretch

**Comment by iProgramMC** [comment]
Basic version implemented in: https://github.com/DiscordMessenger/dm/commit/31a4bd2340109e5daaaef40f224345fa51fb22fe

Now to add repositioning.
