### ISSUE TITLE
Add support for bot messages with custom display name and avatar

### ISSUE THREAD

**Issue by SupahMario** [DiscordMessenger/dm#98]
Pluralkit uses the same webhook ID when reproxying messages, however each message can have their own display name and avatar. Currently, Discord Messenger treats all messages from this ID as the same, so the wrong name and avatar is used instead for all messages from the webhook used.
This is kinda an issue for us, as we _don't_ use it for roleplay and are a system ourselves. This not functioning correctly means we cannot tell who's talking as it merges all messsages into being the same user, and kinda makes it unusable as a result. It appears to make all webhook messages use the last proxied message information if new messages are sent. We're in servers with other systems as well, so this just breaks all ability to communicate in those servers.
If this can be resolved that would be greatly appreciated!! Would like to be able to use this without having to worry about PK not functioning correctly.

![discorditself](https://github.com/DiscordMessenger/dm/assets/40162488/29e17c77-0ccb-4acb-a317-ceada46ad480)
![discordmessengerbugreport](https://github.com/DiscordMessenger/dm/assets/40162488/b54a9a2e-dc85-4979-9487-bfa40ec117d0)

**Comment by iProgramMC** [comment]
Could you show me a json dump of these messages?
