### ISSUE TITLE
Display text attachments inline

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#99]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/51c0518d-c6b1-44bf-9a84-8391a35e24ef)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/f0df6b27-5309-4b54-a71a-072eb9aa6add)

**Comment by iProgramMC** [comment]
Not planned.

Also, this is the fourth time you're reminded to not suggest features (#90 was the first time). A fifth time will cause a block on your account from the organization.
